import { jsonrepair } from 'jsonrepair';
import { BadRequestError } from '../utils/ApiError.js';

/**
 * Repairs unescaped quotes inside string properties of a raw JSON.
 * Example: "query": "up{job="checkout-service"}" -> "query": "up{job=\"checkout-service\"}"
 */
function repairUnescapedQuotes(rawJson) {
  const lines = rawJson.split(/\r?\n/);
  const repairedLines = lines.map((line) => {
    // Match line pattern: "key": "value" or "key": "value",
    const match = line.match(/^(\s*"[a-zA-Z0-9_-]+"\s*:\s*")([\s\S]*)("\s*,?\s*)$/);
    if (match) {
      const prefix = match[1];
      const content = match[2];
      const suffix = match[3];

      // Escape any double quote in content that is not already escaped.
      // We use lookbehind (?<!\\) to avoid escaping already-escaped quotes.
      const escapedContent = content.replace(/(?<!\\)"/g, '\\"');
      return prefix + escapedContent + suffix;
    }
    return line;
  });
  return repairedLines.join('\n');
}

/**
 * Recursively converts undefined values to null in a JavaScript object.
 */
function convertUndefinedToNull(obj) {
  if (obj === undefined || obj === null) {
    return null;
  }
  if (Array.isArray(obj)) {
    return obj.map(convertUndefinedToNull);
  }
  if (typeof obj === 'object') {
    const res = {};
    const keys = Reflect.ownKeys(obj);
    for (const key of keys) {
      res[key] = convertUndefinedToNull(obj[key]);
    }
    return res;
  }
  return obj;
}

/**
 * Repairs and parses a raw JSON payload generated by an LLM.
 * 
 * - Removes markdown wrappers (e.g. ```json ... ```).
 * - Normalizes SourceType enum representations (e.g. <SourceTypeEnum.PROMETHEUS: "PROMETHEUS"> -> "PROMETHEUS").
 * - Repairs malformed JSON where possible using the `jsonrepair` library.
 * - Recursively trims strings.
 * - Converts undefined values to null.
 * - Converts null source arrays to [].
 * 
 * @param {string|object} input 
 * @returns {object} Repaired and parsed JS object
 */
export function repairJsonPayload(input) {
  if (input === undefined || input === null) {
    throw new BadRequestError('Invalid JSON payload');
  }

  let parsed;

  if (typeof input === 'string') {
    let cleaned = input.trim();

    // 1. Remove markdown wrappers
    const markdownRegex = /^```(?:json)?\s*([\s\S]*?)\s*```$/i;
    const match = cleaned.match(markdownRegex);
    if (match) {
      cleaned = match[1].trim();
    }

    // 2. Normalize enum values (e.g. <SourceTypeEnum.PROMETHEUS: "PROMETHEUS">)
    cleaned = cleaned.replace(/<SourceTypeEnum\.([A-Z_]+):\s*\\?["']?([A-Z_]+)\\?["']?>/gi, '$2');

    // 3. Repair unescaped quotes in property values
    cleaned = repairUnescapedQuotes(cleaned);

    // 4. Repair malformed JSON
    let repairedText;
    try {
      repairedText = jsonrepair(cleaned);
    } catch (err) {
      throw new BadRequestError('Invalid JSON payload');
    }

    // Parse repaired JSON
    try {
      parsed = JSON.parse(repairedText);
    } catch (err) {
      throw new BadRequestError('Invalid JSON payload');
    }
  } else {
    // Input is already an object
    parsed = convertUndefinedToNull(input);
  }

  // Ensure the parsed result is a JSON object (not array, string, number, or boolean)
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new BadRequestError('Invalid JSON payload');
  }

  // 5. Post-processing: recursively trim, replace undefined with null, and convert null sources to []
  return processParsedObject(parsed);
}

function processParsedObject(obj) {
  if (obj === undefined) {
    return null;
  }
  if (obj === null) {
    return null;
  }

  if (Array.isArray(obj)) {
    return obj.map(item => processParsedObject(item));
  }

  if (typeof obj === 'object') {
    const result = {};
    for (const [key, value] of Object.entries(obj)) {
      if (key === 'sources' && value === null) {
        result[key] = [];
      } else {
        result[key] = processParsedObject(value);
      }
    }
    return result;
  }

  if (typeof obj === 'string') {
    return obj.trim();
  }

  return obj;
}
